title: MJ Arnaiz
description: Essays and notes by MJ Arnaiz.
url: "https://maryjeiel.github.io"
baseurl: "/blog"
lang: en
timezone: Asia/Manila

author:
  name: MJ Arnaiz
  avatar: /assets/profile.jpg
  github: maryjeiel
  x: MaryJeiel
  facebook: "https://www.facebook.com/itsmjta/"
  instagram: "https://www.instagram.com/maryjeiel.arnaiz/?utm_source=qr&r=nametag"

markdown: kramdown
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
